//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestoviMVC.DBTestovi
{
    using System;
    using System.Collections.Generic;
    
    public partial class KorisnikTest
    {
        public int KorisnikTestId { get; set; }
        public int KorisnikId { get; set; }
        public int TestId { get; set; }
        public System.DateTime Datum { get; set; }
        public short BrojBodova { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Test Test { get; set; }
    }
}
